@host=https://localhost:5001
POST {{host}}/auth/register
Content-Type:  application/json

{
    "firstName":"Horace",
    "lastName":"Akpan",
    "email":"horacewillie7@gmail.com",
    "password":"horace2016@"
}

//CTRL+SHIFT+P
//THEN ON MOUSE HOVER
//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0N2FmNWMwNC1lNzRlLTQyMjEtYWJjZS1iM2RjMzg4MjUwOTIiLCJnaXZlbl9uYW1lIjoiSG9yYWNlIiwiZmFtaWx5X25hbWUiOiJBa3BhbiIsImp0aSI6IjM3ODRmZGE2LWYyMzItNDkxOC04MGZkLTE0Yzc4MDAwMTFmYiIsImV4cCI6MTY1NzQxNzUxMSwiaXNzIjoiQnViZXJEaW5uZXIifQ.OIHwxYqVmgn19YNDCMMEphNNxtmkhiGlY2bMIyV0wp4